//! PRISM Hub wire contract — typed telemetry events, an on-disk spool, and the
//! agent-side HTTP client that batches and ships them.
//!
//! **Shipping discipline.** `prism cmd` / PATH shims must never make a network call —
//! the CHANGELOG records a 0.57s -> 0.05s fight to get a tokenizer *off* that exact path,
//! and a blocking POST would be worse. So this module is split in two:
//!
//!   - [`spool_event`] is synchronous and allocation-only: one `write_all` under a mutex.
//!     Safe to call from the `cmd` hot path and from synchronous helpers in `cache.rs`.
//!   - Everything else (`enroll`, `fetch_config`, `flush`, [`HubSender`]) is async and
//!     touches the network. Only the long-running `serve` daemon and the `prism hub`
//!     subcommand — both already on tokio — call into that half.
//!
//! **The wire contract.** Every event type here derives `Serialize` with
//! `#[serde(rename_all = "camelCase")]`. That is the actual fix for the bug this module
//! replaces: `analytics::record_proxy_event` used to hand-build a `serde_json::json!`
//! literal with snake_case keys and POST it to a hub reading camelCase with `??`
//! fallbacks, so every field silently defaulted. Building the request body by
//! *constructing a typed value* makes that class of mismatch a compile error instead of
//! a three-month-old silent zero. [`HubEvent`] is the single source of truth for the
//! shape; `tests/fixtures/hub-events.json` (regenerated by `cargo test hub::contract`) is
//! what a hub-side schema should validate against.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

// ============================== wire types ================================

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyEvent {
    pub source_ip: String,
    pub api_key_hash: String,
    pub provider: String,
    pub model: String,
    pub orig_tokens: u32,
    pub sent_tokens: u32,
    pub resp_tokens: u32,
    pub cost_usd: f64,
    pub latency_ms: u64,
    /// Whether the *upstream provider's own* prompt cache reported a hit
    /// (`cache_read_input_tokens` / `prompt_tokens_details.cached_tokens` > 0). Distinct
    /// from `cache_served`, which is PRISM's own semantic cache short-circuiting the
    /// request before an upstream call was ever made.
    pub cache_hit: bool,
    pub compression_ratio: f32,
    /// True only when this response never left the machine: PRISM's semantic cache
    /// served it and no upstream request was made.
    pub cache_served: bool,
    pub image_saved_tokens: u32,
    pub prompt_cache_read_tokens: u32,
    pub prompt_cache_write_tokens: u32,
    pub status: u16,
    pub ts: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandEvent {
    pub tool: String,
    pub subcommand: String,
    pub exit_code: i32,
    pub duration_ms: u64,
    pub input_bytes: usize,
    pub output_bytes: usize,
    /// Bytes elided by the filter (`input_bytes - output_bytes`, floored at 0) — the
    /// per-invocation savings the Commands & Filters page exists to show.
    pub filtered_bytes: usize,
    pub truncated: bool,
    pub via_shim: bool,
    pub ts: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CacheEventKind {
    Hit,
    Miss,
    Record,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEvent {
    pub event: CacheEventKind,
    pub similarity: f32,
    pub key_hash: String,
    pub ts: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SessionEventKind {
    Start,
    End,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionEvent {
    pub event: SessionEventKind,
    pub client: String,
    pub project: String,
    pub cwd_hash: String,
    pub ts: String,
}

/// Tagged union of every event PRISM ships to the hub. Internally tagged on `"type"`,
/// so a `Proxy` event serializes as `{"type":"proxy", sourceIp: ..., ...}` — one flat
/// object, easy for a zod discriminated union to validate.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum HubEvent {
    Proxy(ProxyEvent),
    Command(CommandEvent),
    Cache(CacheEvent),
    Session(SessionEvent),
}

/// RFC3339 timestamp for `ts` fields, factored out so every call site stamps the same way.
pub fn now() -> String {
    chrono::Utc::now().to_rfc3339()
}

/// `sent/orig`, the same derived ratio `record_proxy_event` always computed — factored
/// out so both proxy call sites (and tests) share one definition of "1.0 when nothing
/// was measured" rather than repeating the fallback.
pub fn compression_ratio(orig_tokens: u32, sent_tokens: u32) -> f32 {
    if orig_tokens > 0 {
        sent_tokens as f32 / orig_tokens as f32
    } else {
        1.0
    }
}

// ============================== disk spool =================================

static HUB_SPOOL_LOCK: Mutex<()> = Mutex::new(());

fn lock_spool() -> std::sync::MutexGuard<'static, ()> {
    HUB_SPOOL_LOCK.lock().unwrap_or_else(|poison| poison.into_inner())
}

pub fn spool_dir() -> PathBuf {
    crate::analytics::analytics_dir()
}

pub fn spool_path() -> PathBuf {
    spool_dir().join("hub_spool.jsonl")
}

/// A spool drain in flight is rotated here first, so a crash between "read" and
/// "truncate" cannot lose events — see [`rotate_spool`].
fn in_flight_path() -> PathBuf {
    spool_dir().join("hub_spool.jsonl.sending")
}

/// Append one event to the on-disk spool. Synchronous and allocation-light: one
/// `serde_json::to_string` plus one buffered `write_all` under a mutex, mirroring the
/// `PROXY_EVENTS_LOCK` pattern in `analytics.rs`. Safe to call from the `prism cmd` hot
/// path — this function never touches the network.
pub fn spool_event(event: &HubEvent) -> std::io::Result<()> {
    let mut line = serde_json::to_string(event)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    line.push('\n');
    let _guard = lock_spool();
    std::fs::create_dir_all(spool_dir())?;
    let mut f = std::fs::OpenOptions::new().create(true).append(true).open(spool_path())?;
    f.write_all(line.as_bytes())?;
    f.flush()
}

/// Atomically rotate the spool file out from under any concurrent `prism cmd` appender
/// and return its content as newline-delimited JSON. `prism cmd` processes always open
/// the spool path fresh per write (never hold a long-lived handle), so renaming it away
/// is enough: any writer racing this rename either lands in the old inode (now at
/// `in_flight_path()`, folded back in below) or opens a brand new file at the original
/// path — either way nothing is lost.
fn rotate_spool() -> std::io::Result<Option<(PathBuf, String)>> {
    let _guard = lock_spool();
    let path = spool_path();
    let in_flight = in_flight_path();

    // A previous drain that crashed or failed before `confirm_sent` left this behind.
    // Fold it back onto the live spool before rotating again, so it is not skipped.
    if in_flight.is_file() {
        let mut prior = std::fs::read_to_string(&in_flight).unwrap_or_default();
        if !prior.is_empty() && !prior.ends_with('\n') {
            prior.push('\n');
        }
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        std::fs::write(&path, format!("{prior}{current}"))?;
        let _ = std::fs::remove_file(&in_flight);
    }

    if !path.is_file() {
        return Ok(None);
    }
    std::fs::rename(&path, &in_flight)?;
    let content = std::fs::read_to_string(&in_flight)?;
    if content.trim().is_empty() {
        let _ = std::fs::remove_file(&in_flight);
        return Ok(None);
    }
    Ok(Some((in_flight, content)))
}

/// Send succeeded: the rotated file's content is durably on the hub. Drop it.
fn confirm_sent(rotated: &Path) {
    let _ = std::fs::remove_file(rotated);
}

/// Send failed: fold the rotated content back onto whatever is currently live (a
/// `prism cmd` process may have appended to a fresh spool file in the meantime) rather
/// than dropping it, then remove the temp file. This is the "only truncate after a 2xx"
/// half of the contract.
fn restore_spool(rotated: &Path) {
    let _guard = lock_spool();
    if let Ok(prior) = std::fs::read_to_string(rotated) {
        let path = spool_path();
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        let mut combined = prior;
        if !combined.is_empty() && !combined.ends_with('\n') {
            combined.push('\n');
        }
        combined.push_str(&current);
        let _ = std::fs::write(&path, combined);
    }
    let _ = std::fs::remove_file(rotated);
}

// ============================== agent identity ==============================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentCredentials {
    pub hub_url: String,
    pub agent_id: String,
    pub agent_token: String,
}

fn credentials_path() -> PathBuf {
    crate::prism_config_dir().join("hub.json")
}

/// The durable agent identity written by `prism hub enroll`, or `None` if this machine
/// has never enrolled with a hub.
pub fn load_credentials() -> Option<AgentCredentials> {
    let s = std::fs::read_to_string(credentials_path()).ok()?;
    serde_json::from_str(&s).ok()
}

pub fn save_credentials(creds: &AgentCredentials) -> std::io::Result<()> {
    let dir = crate::prism_config_dir();
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        credentials_path(),
        serde_json::to_string_pretty(creds).unwrap_or_default(),
    )
}

// ============================== HTTP plumbing ================================

/// Normalise a hub base URL to its API root. The hub mounts everything under a global
/// `/api` prefix, so a bare host needs it appended, while a URL that already ends in
/// `/api` must not get it twice.
pub(crate) fn api_base(url: &str) -> String {
    let trimmed = url.trim_end_matches('/');
    if trimmed.ends_with("/api") {
        trimmed.to_string()
    } else {
        format!("{trimmed}/api")
    }
}

fn http_client() -> reqwest::Client {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .unwrap_or_default()
}

fn hostname_string() -> String {
    std::process::Command::new("hostname")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown-host".to_string())
}

const MAX_BATCH: usize = 200;

/// POST one batch of already-serialized `HubEvent` JSON lines to `/api/ingest/events`.
async fn post_batch(client: &reqwest::Client, creds: &AgentCredentials, lines: &[&str]) -> Result<()> {
    let body: Vec<serde_json::Value> = lines.iter().filter_map(|l| serde_json::from_str(l).ok()).collect();
    if body.is_empty() {
        return Ok(());
    }
    let url = format!("{}/ingest/events", api_base(&creds.hub_url));
    let resp = client
        .post(&url)
        .bearer_auth(&creds.agent_token)
        .header("X-Prism-Agent-Id", &creds.agent_id)
        .json(&body)
        .send()
        .await
        .with_context(|| format!("POST {url}"))?;
    let status = resp.status();
    if status.is_success() {
        Ok(())
    } else {
        let text = resp.text().await.unwrap_or_default();
        anyhow::bail!("hub ingest returned {status}: {text}");
    }
}

/// Drain the on-disk spool: rotate it out, send in `MAX_BATCH`-sized chunks, and only
/// drop the rotated file once every chunk in it has been accepted. On any failure the
/// whole rotated file (including chunks already accepted this pass) is folded back onto
/// the live spool for a later retry — an accepted at-least-once duplicate is preferable
/// to a silently dropped event.
pub async fn flush(creds: &AgentCredentials) -> FlushOutcome {
    let client = http_client();
    let mut sent = 0usize;
    let mut batches = 0usize;
    let mut failed = false;

    loop {
        match rotate_spool() {
            Ok(Some((rotated, content))) => {
                let lines: Vec<&str> = content.lines().filter(|l| !l.trim().is_empty()).collect();
                let mut all_ok = true;
                for chunk in lines.chunks(MAX_BATCH) {
                    match post_batch(&client, creds, chunk).await {
                        Ok(()) => {
                            batches += 1;
                            sent += chunk.len();
                        }
                        Err(e) => {
                            tracing::warn!("hub flush: {e}");
                            all_ok = false;
                            break;
                        }
                    }
                }
                if all_ok {
                    confirm_sent(&rotated);
                } else {
                    restore_spool(&rotated);
                    failed = true;
                    break;
                }
            }
            Ok(None) => break,
            Err(e) => {
                tracing::warn!("hub flush: could not rotate spool: {e}");
                failed = true;
                break;
            }
        }
    }

    FlushOutcome { sent, batches, failed }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FlushOutcome {
    pub sent: usize,
    pub batches: usize,
    pub failed: bool,
}

// ============================== enroll / config / test ==============================

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct EnrollRequest<'a> {
    join_token: &'a str,
    hostname: String,
    os: &'static str,
    prism_version: &'static str,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EnrollResponse {
    agent_id: String,
    agent_token: String,
}

/// Exchange a short-lived team join token for a durable agent token, and persist both
/// alongside the agent id under the global config dir.
pub async fn enroll(hub_url: &str, join_token: &str) -> Result<AgentCredentials> {
    let client = http_client();
    let url = format!("{}/agents/enroll", api_base(hub_url));
    let req = EnrollRequest {
        join_token,
        hostname: hostname_string(),
        os: std::env::consts::OS,
        prism_version: env!("CARGO_PKG_VERSION"),
    };
    let resp = client
        .post(&url)
        .json(&req)
        .send()
        .await
        .with_context(|| format!("connecting to hub at {url}"))?;
    let status = resp.status();
    if !status.is_success() {
        let text = resp.text().await.unwrap_or_default();
        anyhow::bail!("enroll failed: hub returned {status}: {text}");
    }
    let parsed: EnrollResponse = resp.json().await.context("parsing enroll response")?;
    let creds = AgentCredentials {
        hub_url: hub_url.trim_end_matches('/').to_string(),
        agent_id: parsed.agent_id,
        agent_token: parsed.agent_token,
    };
    save_credentials(&creds)?;
    Ok(creds)
}

/// Fetch hub-enforced policy for this agent and write it to `<data>/hub-config.yaml`,
/// where `config::merge_all` picks it up as the highest-precedence layer.
pub async fn fetch_config(creds: &AgentCredentials) -> Result<crate::config::PrismConfig> {
    let client = http_client();
    let url = format!("{}/agents/{}/config", api_base(&creds.hub_url), creds.agent_id);
    let resp = client
        .get(&url)
        .bearer_auth(&creds.agent_token)
        .send()
        .await
        .with_context(|| format!("connecting to hub at {url}"))?;
    let status = resp.status();
    if !status.is_success() {
        let text = resp.text().await.unwrap_or_default();
        anyhow::bail!("fetch config failed: hub returned {status}: {text}");
    }
    let text = resp.text().await.context("reading hub config response")?;
    // The hub side is a different repo/agent; be lenient about whether it answers with
    // the YAML we persist locally or a JSON encoding of the same shape.
    let cfg: crate::config::PrismConfig = serde_yaml::from_str(&text)
        .or_else(|_| serde_json::from_str(&text))
        .context("hub policy did not parse as PrismConfig (YAML or JSON)")?;
    let path = crate::prism_data_dir().join("hub-config.yaml");
    std::fs::write(&path, serde_yaml::to_string(&cfg).unwrap_or_default())
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(cfg)
}

/// Send one synthetic event and report success/failure. With `hub_url_override` set this
/// needs no prior enrollment — point it at `python3 -m http.server` or `nc -l` and check
/// that the request body keys are camelCase, which is the manual proof the contract is
/// wired correctly end to end.
pub async fn send_test_event(hub_url_override: Option<String>) -> Result<()> {
    let creds = match hub_url_override {
        Some(url) => AgentCredentials {
            hub_url: url.trim_end_matches('/').to_string(),
            agent_id: "test-agent".to_string(),
            agent_token: "test-token".to_string(),
        },
        None => load_credentials()
            .context("not enrolled — run `prism hub enroll` first, or pass --url to test against a scratch endpoint")?,
    };
    let client = http_client();
    let ev = HubEvent::Session(SessionEvent {
        event: SessionEventKind::Start,
        client: "prism-hub-test".to_string(),
        project: "prism".to_string(),
        cwd_hash: "0".repeat(16),
        ts: now(),
    });
    let line = serde_json::to_string(&ev)?;
    post_batch(&client, &creds, &[line.as_str()]).await
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HubStatus {
    pub enrolled: bool,
    pub hub_url: Option<String>,
    pub agent_id: Option<String>,
    pub spool_events: usize,
    pub spool_bytes: u64,
}

pub fn status() -> HubStatus {
    let creds = load_credentials();
    let (events, bytes) = match std::fs::read_to_string(spool_path()) {
        Ok(s) => (s.lines().filter(|l| !l.trim().is_empty()).count(), s.len() as u64),
        Err(_) => (0, 0),
    };
    HubStatus {
        enrolled: creds.is_some(),
        hub_url: creds.as_ref().map(|c| c.hub_url.clone()),
        agent_id: creds.as_ref().map(|c| c.agent_id.clone()),
        spool_events: events,
        spool_bytes: bytes,
    }
}

// ============================== live sender (the `serve` daemon) ==============================

/// Bounded channel + background batching task owned by `prism serve`. Proxy call sites
/// build a `HubEvent` and call [`HubSender::send`]; this never blocks the request path —
/// a full channel (the hub has been unreachable long enough to back up 1024 events)
/// falls back to [`spool_event`], the same disk path `prism cmd` uses, so nothing is
/// dropped, only delayed until the next `prism hub flush` or periodic drain.
pub struct HubSender {
    tx: Option<tokio::sync::mpsc::Sender<HubEvent>>,
}

impl HubSender {
    /// A sender with no background task at all — every `send()` goes straight to the
    /// disk spool. Used by tests and anywhere a `HubSender` is required structurally but
    /// no real hub connection should be attempted.
    pub fn inert() -> Self {
        HubSender { tx: None }
    }

    /// Spawn the background task if this agent is enrolled; otherwise return an inert
    /// sender that spools every event to disk (still recoverable via `prism hub flush`
    /// once `prism hub enroll` has run).
    pub fn spawn() -> Self {
        let Some(creds) = load_credentials() else {
            tracing::info!("hub: not enrolled — proxy telemetry stays local (see `prism hub enroll`)");
            return HubSender { tx: None };
        };

        let (tx, rx) = tokio::sync::mpsc::channel::<HubEvent>(1024);
        tokio::spawn(Self::run(creds, rx));
        HubSender { tx: Some(tx) }
    }

    async fn run(creds: AgentCredentials, mut rx: tokio::sync::mpsc::Receiver<HubEvent>) {
        // Whatever this agent (or `prism cmd` invocations while `serve` was down) already
        // spooled goes out before anything new.
        let startup = flush(&creds).await;
        tracing::info!(
            "hub: startup drain sent {} event(s) in {} batch(es){}",
            startup.sent,
            startup.batches,
            if startup.failed { " (hub unreachable, will retry)" } else { "" }
        );

        let client = http_client();
        let mut batch: Vec<HubEvent> = Vec::with_capacity(MAX_BATCH);
        let mut tick = tokio::time::interval(std::time::Duration::from_secs(2));
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);

        loop {
            tokio::select! {
                biased;
                maybe_ev = rx.recv() => {
                    match maybe_ev {
                        Some(ev) => {
                            batch.push(ev);
                            if batch.len() >= MAX_BATCH {
                                Self::send_batch(&client, &creds, &mut batch).await;
                            }
                        }
                        None => break, // sender dropped: process is shutting down
                    }
                }
                _ = tick.tick() => {
                    if !batch.is_empty() {
                        Self::send_batch(&client, &creds, &mut batch).await;
                    }
                    let _ = flush(&creds).await;
                }
            }
        }
        if !batch.is_empty() {
            Self::send_batch(&client, &creds, &mut batch).await;
        }
    }

    /// Send with exponential backoff; on final failure, spool the batch rather than
    /// drop it.
    async fn send_batch(client: &reqwest::Client, creds: &AgentCredentials, batch: &mut Vec<HubEvent>) {
        const MAX_ATTEMPTS: u32 = 3;
        let lines: Vec<String> = batch.iter().filter_map(|e| serde_json::to_string(e).ok()).collect();
        let refs: Vec<&str> = lines.iter().map(String::as_str).collect();

        for attempt in 1..=MAX_ATTEMPTS {
            match post_batch(client, creds, &refs).await {
                Ok(()) => {
                    batch.clear();
                    return;
                }
                Err(e) => {
                    tracing::warn!("hub: POST attempt {attempt}/{MAX_ATTEMPTS} failed: {e}");
                    if attempt < MAX_ATTEMPTS {
                        let backoff = std::time::Duration::from_millis(300 * 2u64.pow(attempt));
                        tokio::time::sleep(backoff).await;
                    }
                }
            }
        }
        for ev in batch.drain(..) {
            let _ = spool_event(&ev);
        }
    }

    /// Queue an event. Never blocks: falls back to the disk spool on backpressure or
    /// when there is no live sender (not enrolled).
    pub fn send(&self, event: HubEvent) {
        let Some(tx) = &self.tx else {
            let _ = spool_event(&event);
            return;
        };
        if let Err(e) = tx.try_send(event) {
            use tokio::sync::mpsc::error::TrySendError;
            let dropped = match e {
                TrySendError::Full(ev) | TrySendError::Closed(ev) => ev,
            };
            let _ = spool_event(&dropped);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The contract regression guard: one instance of every `HubEvent` variant,
    /// serialized to the fixture the hub's own test suite parses. A field rename on
    /// either side must fail this test (or the hub's) rather than silently drift.
    #[test]
    fn contract_fixture_matches_camel_case_shape() {
        let events = vec![
            HubEvent::Proxy(ProxyEvent {
                source_ip: "203.0.113.7".to_string(),
                api_key_hash: "a1b2c3d4".to_string(),
                provider: "anthropic".to_string(),
                model: "claude-3-5-sonnet".to_string(),
                orig_tokens: 4000,
                sent_tokens: 2200,
                resp_tokens: 512,
                cost_usd: 0.0123,
                latency_ms: 842,
                cache_hit: true,
                compression_ratio: compression_ratio(4000, 2200),
                cache_served: false,
                image_saved_tokens: 300,
                prompt_cache_read_tokens: 1800,
                prompt_cache_write_tokens: 0,
                status: 200,
                ts: "2026-09-10T00:00:00Z".to_string(),
            }),
            HubEvent::Command(CommandEvent {
                tool: "git".to_string(),
                subcommand: "status".to_string(),
                exit_code: 0,
                duration_ms: 37,
                input_bytes: 4096,
                output_bytes: 512,
                filtered_bytes: 3584,
                truncated: true,
                via_shim: true,
                ts: "2026-09-10T00:00:00Z".to_string(),
            }),
            HubEvent::Cache(CacheEvent {
                event: CacheEventKind::Hit,
                similarity: 0.91,
                key_hash: "e5f6a7b8".to_string(),
                ts: "2026-09-10T00:00:00Z".to_string(),
            }),
            HubEvent::Session(SessionEvent {
                event: SessionEventKind::Start,
                client: "claude-code".to_string(),
                project: "prism".to_string(),
                cwd_hash: "0123456789abcdef".to_string(),
                ts: "2026-09-10T00:00:00Z".to_string(),
            }),
        ];

        let json = serde_json::to_string_pretty(&events).expect("events must serialize");

        // Every wire field name is camelCase — the exact bug being fixed.
        for must_contain in [
            "\"sourceIp\"", "\"apiKeyHash\"", "\"origTokens\"", "\"sentTokens\"",
            "\"respTokens\"", "\"costUsd\"", "\"latencyMs\"", "\"cacheHit\"",
            "\"compressionRatio\"", "\"cacheServed\"", "\"imageSavedTokens\"",
            "\"promptCacheReadTokens\"", "\"promptCacheWriteTokens\"",
            "\"exitCode\"", "\"durationMs\"", "\"inputBytes\"", "\"outputBytes\"",
            "\"filteredBytes\"", "\"viaShim\"", "\"keyHash\"", "\"cwdHash\"",
            "\"type\": \"proxy\"", "\"type\": \"command\"", "\"type\": \"cache\"", "\"type\": \"session\"",
        ] {
            assert!(json.contains(must_contain), "fixture missing {must_contain}:\n{json}");
        }
        // And no snake_case survivors of the old broken contract.
        for must_not_contain in ["orig_tokens", "api_key_hash", "cost_usd", "exit_code"] {
            assert!(!json.contains(must_not_contain), "fixture still has snake_case {must_not_contain}:\n{json}");
        }

        let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/hub-events.json");
        std::fs::create_dir_all(fixture_path.parent().unwrap()).unwrap();
        std::fs::write(&fixture_path, &json).expect("writing tests/fixtures/hub-events.json");
    }

    #[test]
    fn spool_rotate_confirm_round_trip() {
        let dir = std::env::temp_dir().join(format!(
            "prism-hub-spool-test-{}-{:?}",
            std::process::id(),
            std::time::SystemTime::now()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        // SAFETY: single-threaded env mutation scoped to this test's own temp dir name.
        unsafe { std::env::set_var("PRISM_DATA_DIR", &dir) };

        let ev = HubEvent::Command(CommandEvent {
            tool: "ls".to_string(),
            subcommand: String::new(),
            exit_code: 0,
            duration_ms: 5,
            input_bytes: 10,
            output_bytes: 10,
            filtered_bytes: 0,
            truncated: false,
            via_shim: false,
            ts: now(),
        });
        spool_event(&ev).unwrap();
        assert_eq!(status().spool_events, 1);

        let (rotated, content) = rotate_spool().unwrap().expect("one event should be present");
        assert!(content.contains("\"tool\":\"ls\""));
        assert_eq!(status().spool_events, 0, "rotate must remove the live spool file");

        // Failure path: content must come back.
        restore_spool(&rotated);
        assert_eq!(status().spool_events, 1);

        let (rotated2, _) = rotate_spool().unwrap().unwrap();
        confirm_sent(&rotated2);
        assert_eq!(status().spool_events, 0);

        unsafe { std::env::remove_var("PRISM_DATA_DIR") };
        let _ = std::fs::remove_dir_all(&dir);
    }
}
